### PR TITLE
chore(deps): update opentelemetry collector and adapt tests

### PR DESCRIPTION
**Pull request by pichlermarc**
### Summary 

- All changes from #154 
- Adapted tests:
  - `transformprocessor`'s `extract_count_metric()` now uses the default unit (`'1'`)  instead of using the unit from the original histogram. This decision was made as the original histogram unit does never apply to a histogram's `count` field. For additional info see, see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31575
  - adapt smoke tests to treat `componentMetadata.Name` as `component.Type`, see changes from https://github.com/open-telemetry/opentelemetry-collector/pull/9472

### Blockers

- Tests are currently failing due to https://github.com/open-telemetry/opentelemetry-collector/issues/9855
  - **User Impact:** `dynatrace-otel-collector components` would result in wrong output.
  - Can be fixed by applying the upstream fix via a replace directive, see https://github.com/Dynatrace/dynatrace-otel-collector/pull/159/commits/6cf0f65cfe76fc48302ea93473690cf954634f8e
- We'd be affected by https://github.com/open-telemetry/opentelemetry-collector/issues/9863
   - **User Impact:** `dynatrace-otel-collector validate --config=my-config.yaml` would validate correctly, but there would not be any suggestions which components are available if validation fails.
   - Can be fixed by applying the upstream fix via a replace directive, see https://github.com/Dynatrace/dynatrace-otel-collector/pull/159/commits/895b9f2bd83da680e8120d27a81ae6c18a5c33ac

### Additional Information

Replaces #154

### CODE REVIEW

**Review by arminru — APPROVED** [review]

**Comment by pichlermarc** [comment]
Converting back to draft (see blockers).

**Comment by dyladan** [comment]
> Converting back to draft (see blockers in PR body).

I see you used the replace directive to fix the upstream components. Is this still draft or do we want to review/merge it?

**Comment by pichlermarc** [comment]
> > Converting back to draft (see blockers in PR body).
> 
> I see you used the replace directive to fix the upstream components. Is this still draft or do we want to review/merge it?

This is still a draft. We discussed offline that we will
- not go ahead with updating to 0.97.0 for now due to the known issues from the blockers section
- not apply the unreleased fixes from upstream at this time

**Comment by pichlermarc** [comment]
Closing this PR, I'll re-open a new one for the current release.

**Pull request closed without merging**
